workspace:
  base: /test
  path: oe_auth

services:
  web:
    image: fpfis/php71-build:latest
    environment:
     - DOCUMENT_ROOT=/test/oe_auth
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  oeauth-server:
    image: openeuropa/pcas-server:latest

matrix:
  DRUPAL_VERSION:
    - 8.6.x

pipeline:
  composer-install:
    image: fpfis/php71-build
    volumes:
      - /cache:/cache
    commands:
      - composer require --dev webflo/drupal-core-require-dev:${DRUPAL_VERSION=8.6.x}
  site-install:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run drupal:site-setup
      - ./vendor/bin/run drupal:site-install
  grumphp:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/grumphp run
  phpunit:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/phpunit
  behat:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/behat
