workspace:
  base: /test
  path: oe_authentication

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
     - DOCUMENT_ROOT=/test/oe_authentication
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  authentication:
    image: openeuropa/pcas-server:latest

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer install

  site-install:
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      # Reset permission since installation runs as root. @todo Fix this.
      - ./vendor/bin/drush -y config-set system.performance css.preprocess 0
      - ./vendor/bin/drush -y config-set system.performance js.preprocess 0
      - ./vendor/bin/behat
