oe_authentication.settings:
  type: config_object
  label: 'OpenEuropa Authentication settings'
  mapping:
    register_path:
      type: string
      label: 'Path for new account request'
    assurance_level:
      type: string
      label: 'Application assurance levels'
    ticket_types:
      type: string
      label: 'Application available ticket types'