oe_authentication.settings:
  type: config_object
  label: 'OpenEuropa Authentication settings'
  mapping:
    validation_path:
      type: string
      label: 'Application validation path'
    assurance_level:
      type: string
      label: 'Application assurance levels'
    ticket_types:
      type: string
      label: 'Application available ticket types'